version: '3.8'

services:
  controleveiculos:
    build: .
    container_name: controleveiculos
    ports:
      - "3070:3000"
    volumes:
      - .:/app:rw
      - node_modules:/app/node_modules
    env_file: 
      - .env  # Carrega variáveis do arquivo .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1G
        reservations:
          cpus: "0.50"
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - controleveiculos_network

  mysql_controleveiculos:
    image: mysql:8.0
    container_name: mysql_controleveiculos
    ports:
      - "3367:3306"
    env_file: 
      - .env  # Carrega as variáveis para o MySQL também
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: America/Sao_Paulo
    restart: unless-stopped
    networks:
      - controleveiculos_network

networks:
  controleveiculos_network:
    driver: bridge

volumes:
  node_modules:
